media:
  input: assets/s/media
  output: /s/media
  categories: [ image, document, video, audio, compressed ]
content:
  - name: pages
    label: Pages
    path: content
    type: collection
    fields:
      - name: title
        label: Title
        type: string
      - name: desc
        label: Description
        type: string
      - name: body
        label: Body
        type: rich-text
      - name: date
        label: Date
        type: date
      - name: category
        label: Category
        type: string
        list:
          collapsible: false
      - name: tags
        label: Tags
        type: string
        list:
          collapsible: false

