media:
  input: assets/s/media
  output: /s/media
  categories: [ image, document, video, audio, compressed ]
components:
  - title:
    label: Title
    type: string
  - desc:
    label: Description
    type: string
  - body:
    label: Body
    type: rich-text
  - date:
    label: Date
    type: date
  - category:
    label: Category
    type: string
    list:
      collapsible: false
  - tags:
    label: Tags
    type: string
    list:
      collapsible: false
  - height:
    label: Height
    type: number
content:
  - name: articles
    label: Articles
    path: content/articles
    type: collection
    fields:
      - name: title
        component: title
      - name: desc
        component: desc
      - name: body
        componet: body
      - name: date
        componet: date
      - name: tags
        componet: tags
  - name: showcase
    label: Showcase
    path: content/showcase
    type: collection
    fields:
      - name: title
        component: title
      - name: desc
        component: desc
      - name: body
        componet: body
      - name: date
        componet: date
      - name: tags
        componet: tags
      - name: height
        component: height
  - name: pages
    label: Pages
    path: content
    type: collection
    fields:
      - name: title
        component: title
      - name: desc
        component: desc
      - name: body
        componet: body
