media:
  input: assets/s/media
  output: /s/media
  categories: [ image, document, video, audio, compressed ]
components:
  - name: basic
    type: object
    fields:
      - name: title
        label: Title
        type: string
      - name: desc
        label: Description
        type: string
      - name: body
        label: Body
        type: rich-text
  - name: content
    type: object
    fields:
      - name: date
        label: Date
        type: date
      - name: category
        label: Category
        type: string
        list:
          collapsible: false
      - name: tags
        label: Tags
        type: string
        list:
          collapsible: false
      - component: basic
content:
  - name: articles
    label: Articles
    path: content/articles
    type: collection
    fields:
      - component: content
  - name: showcase
    label: Showcase
    path: content/showcase
    type: collection
    fields:
      - component: content
      - name: height
        label: Height
        type: number
  - name: pages
    label: Pages
    path: content
    type: collection
    fields:
      - component: content
